project 'AlamoPromiseObjectMapper.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AlamoPromiseObjectMapper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamoPromiseObjectMapper

  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'PromiseKit'
  pod 'SwiftyBeaver'
  pod 'AlamofireObjectMapper'
  pod 'PromiseKit/Alamofire'
  pod 'AlamofireImage'

  target 'AlamoPromiseObjectMapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamoPromiseObjectMapperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
